name: Check for Changeset

on:
  pull_request:
    branches:
      - main

jobs:
  check-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: git fetch origin main

      - name: Check for changeset file
        run: |
          file=$(git diff --name-only origin/main...HEAD | grep '^.changeset/.*\.md$' || true)
          if [ -z "$file" ]; then
            echo "No changeset found. Please add a changeset."
            exit 1
          else
            echo "Changeset found: $file"
          fi